/**
 * Hotel-Daten für Sizilien Urlaub Juni 2026
 *
 * Neue Unterkunft hinzufügen:
 * 1. Objekt nach dem Schema unten ans Array anhängen
 * 2. Seite neu laden – Karte, Tabellen und Detailkarten werden automatisch generiert
 *
 * Oder: das Formular auf der Seite benutzen (Abschnitt "Unterkunft hinzufügen")
 *
 * Reihenfolge: Sebas-Vorschläge zuerst, dann Rest
 */

const HOTELS = [
  // ═══════════════════════════════════════════════
  //  SEBAS-VORSCHLÄGE (oben im Ranking)
  // ═══════════════════════════════════════════════
  {
    id: 1,
    name: "Lauras Wohnung",
    type: "Eigentumswohnung",
    location: "Palermo Zentrum",
    address: "Nähe Teatro Massimo / Politeama",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/1172421773428788732?check_in=2026-06-08&check_out=2026-06-14&adults=5",
    selectedBy: "Sebas",
    dateFrom: "2026-06-08",
    dateTo: "2026-06-14",
    nights: 6,
    persons: 5,
    totalPrice: 951,
    originalPrice: null,
    rating: 4.77,
    ratingScale: 5,
    ratingCount: 39,
    ratingCategories: { sauberkeit: 4.8, genauigkeit: 4.8, checkin: 4.9, kommunikation: 4.8, lage: 4.9, preisLeistung: 4.8 },
    sqm: null,
    bedrooms: 2,
    bathrooms: 2,
    beds: "Doppelbett + Schlafsofa (Loft) + Schlafsofa (WZ)",
    maxGuests: 6,
    features: ["Aufzug (4. OG)", "Klimaanlage", "WLAN", "Küche + Spülmaschine", "Waschmaschine", "Safe"],
    parking: "",
    cancellation: { free: true, note: "Kostenlos bis 03.06." },
    checkin: "ab 15:00",
    checkout: "vor 10:00 (streng!)",
    host: "Francesco (100% Antwortrate, <1h)",
    distances: { palermo: "~800 m", strand: ">5 km", bahnhof: "zentral", flughafen: "~29 km" },
    pros: ["Beste Lage! Alles zu Fuß", "Sehr edel und elegant", "2 SZ + 2 Bäder = Komfort", "Aufzug, Spülmaschine, Safe", "Bereits für 5 Pers. getestet"],
    cons: ["Deutlich teurer (951 Euro/6N)", "Kein Parkplatz", "Kein Rauchmelder!", "Strenge Check-out-Zeiten", "Kein Strand in der Nähe"],
    quotes: [
      { text: "Francesco ist ein super Gastgeber. Die Wohnung hat uns sehr gut gefallen. Wir waren zu fünft da.", author: "Sonja, DE" },
      { text: "Die Wohnung war atemberaubend. Sauber und sehr gut eingerichtet. Zu Fuß zu allen Denkmälern.", author: "Thibaud, FR" }
    ],
    photos: [
      { icon: "\u{1F3E0}", desc: "Eleganter Flur mit Design-Interieur" },
      { icon: "\u{1F6CC}", desc: "Komfortables Doppelzimmer mit Kleiderschrank" },
      { icon: "\u{1F6CC}", desc: "Loft mit Schlafsofa und eigenem Bad" },
      { icon: "\u{1F3E0}", desc: "Helles, elegantes Wohnzimmer mit Schlafsofa" },
      { icon: "\u{1F373}", desc: "Voll ausgestattete Küche" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#6c3483,#8e44ad)", num: "#5b2c6f", marker: "#8e44ad" },
    mapLat: 38.1210,
    mapLng: 13.3575
  },
  {
    id: 2,
    name: "Anna's House",
    type: "2 Wohnungen + Dachterrasse",
    location: "Isola delle Femmine",
    address: "Historisches Zentrum, 50m vom Hafen",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/19235745?check_in=2026-06-08&check_out=2026-06-13&adults=5",
    selectedBy: "Sebas",
    dateFrom: "2026-06-08",
    dateTo: "2026-06-13",
    nights: 5,
    persons: 5,
    totalPrice: 1047,
    originalPrice: null,
    rating: 4.78,
    ratingScale: 5,
    ratingCount: 18,
    ratingCategories: { sauberkeit: 4.7, genauigkeit: 4.9, checkin: 5.0, kommunikation: 5.0, lage: 4.8, preisLeistung: 4.8 },
    sqm: null,
    bedrooms: 2,
    bathrooms: 2,
    beds: "3 Betten in 2 Wohnungen (3+2 Plätze)",
    maxGuests: 5,
    features: ["Dachterrasse mit Meerblick!", "2 separate Wohnungen", "Klimaanlage", "WLAN", "Küche", "Waschmaschine"],
    parking: "Gratis Parkplatz",
    cancellation: { free: true, note: "Kostenlos bis 09.05." },
    checkin: "ab 16:00",
    checkout: "vor 11:00",
    host: "Francesco Paolo - Superhost (100%, <1h)",
    distances: { palermo: "~17 km", strand: "~15 Min. Fuß", bahnhof: "~10 Min. Fuß", flughafen: "~15 km" },
    pros: ["Dachterrasse mit Meerblick!", "2 separate Wohnungen", "2 Bäder, Superhost", "Tauchen, Segeln, Bootverleih", "Direkt am Hafen und Dorfplatz"],
    cons: ["Teuerste Option! (1.047 Euro)", "17 km bis Palermo", "Treppensteigen nötig", "Belebte Straße (Lärm)", "15-20 Min. zum Strand"],
    quotes: [{ text: "Sehr schönes Haus mit Balkonen und Dachterrasse! Wohnungen liebevoll und modern eingerichtet.", author: "Thomas & Alena, DE" }],
    photos: [
      { icon: "\u{1F3D6}", desc: "Hafen- und Meerblick von der Dachterrasse" },
      { icon: "\u{1F6CC}", desc: "Schlafzimmer - liebevoll und modern" },
      { icon: "\u{1F373}", desc: "Küche mit allem Nötigen" },
      { icon: "\u{1F305}", desc: "Sonnenuntergang von der Terrasse" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#2471a3,#3498db)", num: "#1a5276", marker: "#2980b9" },
    mapLat: 38.1838,
    mapLng: 13.2465
  },
  {
    id: 3,
    name: "Villetta \u201EAnnina\u201C",
    type: "Privatunterkunft",
    location: "Trabia",
    address: "Trabia, Sizilien",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/654922789165519047?adults=5&check_in=2026-06-22&check_out=2026-06-29",
    selectedBy: "Sebas",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 1168,
    originalPrice: null,
    rating: 4.95,
    ratingScale: 5,
    ratingCount: 82,
    ratingCategories: { sauberkeit: 5.0, genauigkeit: 4.9, checkin: 5.0, kommunikation: 4.9, lage: 4.8, preisLeistung: 5.0 },
    sqm: null,
    bedrooms: 2,
    bathrooms: 3,
    beds: "1 Doppelzimmer + 2 Einzelbetten + Schlafsofa",
    maxGuests: 6,
    features: ["Strandzugang (150m)", "Meerblick", "Küche", "WLAN", "Carport (4 Plätze)", "HDTV", "Waschmaschine", "Terrasse/Veranda", "Klimaanlage", "Haustiere erlaubt"],
    parking: "Gratis Carport (4 Stellplätze)",
    cancellation: { free: true, note: "Kostenlos bis 17.06." },
    checkin: "Flexibel",
    checkout: "vor 10:00",
    host: "Francesco - Superhost (9 Jahre, 100%, <1h)",
    distances: { palermo: "~40 km", strand: "150 m", flughafen: "~50 km" },
    pros: ["Top 5% auf Airbnb!", "4,95/5 (82 Reviews)", "Nur 150m zum Strand!", "3 Badezimmer", "Große Terrasse mit Meerblick", "Neubau, alles neu"],
    cons: ["~40 km bis Palermo", "Kein Rauch-/CO-Melder", "Treppensteigen erforderlich", "Autobahnnähe (evtl. Lärm)"],
    quotes: [
      { text: "Exzellentes Haus mit drei Balkonen und Terrassen. Sehr gut eingerichtet.", author: "Matthias, DE" },
      { text: "Tolles Appartment, alles ist neu und genau wie in der Beschreibung!", author: "Malte, DE" }
    ],
    photos: [
      { icon: "\u{1F3D6}", desc: "Goldener Sandstrand von Vetrana" },
      { icon: "\u{1F6CC}", desc: "Doppelzimmer mit Meerblick" },
      { icon: "\u{1F33F}", desc: "Terrasse mit Obstbäumen" },
      { icon: "\u{1F30A}", desc: "Panorama-Meerblick" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#0e6655,#1abc9c)", num: "#0b5345", marker: "#1abc9c" },
    mapLat: 37.9978,
    mapLng: 13.6480
  },
  {
    id: 4,
    name: "MetaM Apt",
    type: "Apartment",
    location: "Palermo Stadtzentrum",
    address: "Palermo Stadtzentrum, Sizilien",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/1184002955171676231?adults=5&check_in=2026-06-22&check_out=2026-06-29",
    selectedBy: "Sebas",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 1106,
    originalPrice: null,
    rating: 4.64,
    ratingScale: 5,
    ratingCount: 11,
    ratingCategories: { sauberkeit: 4.8, genauigkeit: 4.8, checkin: 4.6, kommunikation: 4.2, lage: 4.7, preisLeistung: 4.4 },
    sqm: null,
    bedrooms: 2,
    bathrooms: 1,
    beds: "2\u00d7 Queensize-Bett + 1 Einzelbett (Loft)",
    maxGuests: 5,
    features: ["K\u00fcche", "WLAN", "TV", "Aufzug", "Waschmaschine", "Klimaanlage", "Balkon + Terrasse", "F\u00f6hn", "Freskendecke"],
    parking: "",
    cancellation: { free: true, note: "Kostenlos bis 17.06." },
    checkin: "15:00 - 20:00",
    checkout: "vor 10:00",
    host: "Wonderful Italy Sicilia (100%, <1h)",
    distances: { palermo: "zentral", strand: "~3 km", bahnhof: "3,5 km", flughafen: "~40 Min." },
    pros: ["100% Lage-Bewertung 5 Sterne!", "Freskendecke + historisches Geb\u00e4ude", "Aufzug vorhanden", "Mitten in Palermo"],
    cons: ["Kommunikation nur 4,2", "Kein Rauch-/CO-Melder", "Kein Parkplatz", "1. OG = relativ dunkel", "Check-in nur bis 20:00 (Aufpreis 20\u20ac)"],
    quotes: [
      { text: "Die Lage ist perfekt um \u00fcberall zu Fu\u00df hinzugelangen.", author: "Vivien, DE" },
      { text: "Sehr sch\u00f6ne Wohnung, sch\u00f6n eingerichtet, im Herzen von Palermo.", author: "Alessandra, IT" }
    ],
    photos: [
      { icon: "\u{1F3DB}", desc: "Historisches Geb\u00e4ude mit Fresken" },
      { icon: "\u{1F6CC}", desc: "Queensize-Bett mit Loft" },
      { icon: "\u{1F373}", desc: "Offene K\u00fcche mit Essbereich" },
      { icon: "\u{1F305}", desc: "Balkon mit Platzblick" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#cb4335,#e74c3c)", num: "#a93226", marker: "#e74c3c" },
    mapLat: 38.1157,
    mapLng: 13.3615
  },
  {
    id: 5,
    name: "Casa Mareluna",
    type: "Privatunterkunft (3 Etagen)",
    location: "Porticello",
    address: "Porticello, Sizilien",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/1364533074420730446?adults=5&check_in=2026-06-22&check_out=2026-06-29",
    selectedBy: "Sebas",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 1159,
    originalPrice: null,
    rating: 5.0,
    ratingScale: 5,
    ratingCount: 4,
    ratingCategories: { sauberkeit: 5.0, genauigkeit: 5.0, checkin: 5.0, kommunikation: 5.0, lage: 4.8, preisLeistung: 4.8 },
    sqm: null,
    bedrooms: 3,
    bathrooms: 2,
    beds: "Doppelbett + 2 Einzelbetten + Einzelbett",
    maxGuests: 5,
    features: ["Hofblick", "Stadtblick", "Strandzugang", "K\u00fcche", "WLAN", "Arbeitsplatz", "Parkplatz", "TV", "Waschmaschine", "Klimaanlage", "Panoramaterrassen"],
    parking: "Gratis Parkplatz",
    cancellation: { free: true, note: "Kostenlos bis 08.06." },
    checkin: "15:00 - 20:00",
    checkout: "vor 10:00",
    host: "Oscar - Superhost (4 Jahre, 100%, <1h)",
    distances: { palermo: "~20 km", strand: "wenige Minuten" },
    pros: ["Perfekte 5,0/5 Sterne!", "3 Schlafzimmer + 2 B\u00e4der", "Komplett renoviert, 3 Etagen", "Charmantes Fischerdorf", "Gro\u00dfe Panoramaterrassen"],
    cons: ["Nur 4 Bewertungen", "~20 km bis Palermo", "Max. 5 G\u00e4ste (knapp)"],
    quotes: [
      { text: "Oscar ist ein freundlicher Gastgeber. Das Haus ist komplett ausgestattet und hat alles zum Entspannen.", author: "Romy, DE" },
      { text: "Toller Aufenthalt in Porticello. Das Haus ist sch\u00f6n und gut eingerichtet.", author: "Laurent, FR" }
    ],
    photos: [
      { icon: "\u{1F6A2}", desc: "Fischerhafen Porticello" },
      { icon: "\u{1F6CC}", desc: "Elegantes Schlafzimmer" },
      { icon: "\u{1F305}", desc: "Panoramaterrasse mit Meerblick" },
      { icon: "\u{1F373}", desc: "Moderne K\u00fcche" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#1a5276,#2e86c1)", num: "#154360", marker: "#2e86c1" },
    mapLat: 38.0862,
    mapLng: 13.5305
  },
  {
    id: 6,
    name: "Ciuri ciuri home",
    type: "Privatunterkunft",
    location: "Balestrate",
    address: "Balestrate, Sizilien",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/837662269004809093?adults=5&check_in=2026-06-22&check_out=2026-06-29",
    selectedBy: "Sebas",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 1084,
    originalPrice: null,
    rating: 4.93,
    ratingScale: 5,
    ratingCount: 58,
    ratingCategories: { sauberkeit: 5.0, genauigkeit: 5.0, checkin: 4.8, kommunikation: 5.0, lage: 4.7, preisLeistung: 4.9 },
    sqm: null,
    bedrooms: 3,
    bathrooms: 1,
    beds: "1 Doppelzimmer + 2\u00d7 Einzelbetten",
    maxGuests: 6,
    features: ["Gartenblick", "Seeblick", "K\u00fcche", "WLAN", "Parkplatz", "TV", "E-Ladestation", "Waschmaschine", "Klimaanlage", "Veranda + Garten", "Haustiere erlaubt"],
    parking: "Gratis Parkplatz",
    cancellation: { free: true, note: "Kostenlos bis 17.06." },
    checkin: "14:00 - 01:00",
    checkout: "vor 10:00",
    host: "Salvatore - Superhost (3 Jahre, 100%, <1h)",
    distances: { palermo: "~40 km", strand: "1,5 km", flughafen: "~30 km" },
    pros: ["G\u00e4ste-Favorit! 4,93/5 (58 Reviews)", "3 Schlafzimmer", "Gro\u00dfe Veranda + Garten", "Herzliche Gastgeber!", "G\u00fcnstigste der Neuen (1.084\u20ac)", "E-Ladestation"],
    cons: ["~40 km bis Palermo", "Nur 1 Badezimmer!", "1,5 km zum Strand", "L\u00e4ndliche Lage"],
    quotes: [
      { text: "Wunderbar herzliche Gastgeber! Die Wohnung sehr geschmack- und liebevoll eingerichtet.", author: "Lucie, DE" },
      { text: "Tolle Unterkunft, sehr sauber, genau wie beschrieben, sehr ger\u00e4umig.", author: "Lander, DE" }
    ],
    photos: [
      { icon: "\u{1F33F}", desc: "Garten mit Olivenb\u00e4umen" },
      { icon: "\u{1F6CC}", desc: "Gem\u00fctliches Schlafzimmer" },
      { icon: "\u{1F305}", desc: "Veranda mit Meerblick" },
      { icon: "\u{1F373}", desc: "Voll ausgestattete K\u00fcche" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#d35400,#e67e22)", num: "#af601a", marker: "#e67e22" },
    mapLat: 38.0560,
    mapLng: 13.0084
  },
  {
    id: 7,
    name: "3-Zimmer-Wohnung Alcamo",
    type: "Apartment",
    location: "Alcamo Marina",
    address: "Alcamo Marina, Sizilien",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/1212654192863701617?adults=5&check_in=2026-06-22&check_out=2026-06-29",
    selectedBy: "Sebas",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 1133,
    originalPrice: null,
    rating: 4.67,
    ratingScale: 5,
    ratingCount: 3,
    ratingCategories: { sauberkeit: 4.3, genauigkeit: 4.3, checkin: 5.0, kommunikation: 4.7, lage: 5.0, preisLeistung: 5.0 },
    sqm: null,
    bedrooms: 3,
    bathrooms: 2,
    beds: "2 Einzelbetten + Doppelbett + Doppelbett",
    maxGuests: 6,
    features: ["Seeblick", "K\u00fcche", "WLAN", "Parkplatz", "TV", "Waschmaschine", "Klimaanlage", "F\u00f6hn", "\u00dcberdachte Terrasse", "Grill"],
    parking: "Gratis Parkplatz",
    cancellation: { free: false, note: "24h kostenlos, danach anteilig" },
    checkin: "16:00 - 20:00",
    checkout: "vor 10:00",
    host: "Novasol (8 Jahre, 100%, <1h)",
    distances: { palermo: "~50 km", strand: "5 m (!)", flughafen: "~40 km" },
    pros: ["Direkt am Strand! (5m)", "3 Schlafzimmer + 2 B\u00e4der", "Gro\u00dfe \u00fcberdachte Terrasse", "Naturschutzgebiet Zingaro in der N\u00e4he", "Preis-Leistung: 5,0/5"],
    cons: ["Nur 3 Bewertungen", "~50 km bis Palermo", "Sauberkeit nur 4,3", "Kein CO-Melder", "Gewerblicher Anbieter (Novasol)"],
    quotes: [
      { text: "Der direkte Zugang zum Strand und zum Au\u00dfenbereich sind den Preis wert.", author: "Daniele, IT" },
      { text: "Villa direkt am Meer, gem\u00fctlich. Empfehlenswert.", author: "Denis, MD" }
    ],
    photos: [
      { icon: "\u{1F3D6}", desc: "Strand direkt vor der T\u00fcr" },
      { icon: "\u{1F6CC}", desc: "Helles Schlafzimmer" },
      { icon: "\u{1F305}", desc: "Terrasse mit Meerblick" },
      { icon: "\u{1F373}", desc: "Familienfreundliche K\u00fcche" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#7d3c98,#a569bd)", num: "#6c3483", marker: "#a569bd" },
    mapLat: 38.0249,
    mapLng: 12.9366
  },
  {
    id: 8,
    name: "Villa N\u00e0mali",
    type: "Villa",
    location: "Trappeto",
    address: "Trappeto, Sizilien",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/16764599?adults=5&check_in=2026-06-22&check_out=2026-06-29",
    selectedBy: "Sebas",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 1257,
    originalPrice: null,
    rating: 4.93,
    ratingScale: 5,
    ratingCount: 107,
    ratingCategories: { sauberkeit: 4.9, genauigkeit: 4.9, checkin: 4.9, kommunikation: 5.0, lage: 4.8, preisLeistung: 4.9 },
    sqm: null,
    bedrooms: 3,
    bathrooms: 2,
    beds: "2 Doppelzimmer + 1 Zweibettzimmer",
    maxGuests: 6,
    features: ["Seeblick", "Strandzugang (100m)", "K\u00fcche + Au\u00dfenk\u00fcche", "Schnelles WLAN (57 Mbit/s)", "Parkplatz (3 Pl\u00e4tze)", "HDTV", "Waschmaschine", "Klimaanlage", "Garten", "Au\u00dfendusche"],
    parking: "Gratis Parkplatz (3 Stellpl\u00e4tze)",
    cancellation: { free: true, note: "Kostenlos bis 17.06." },
    checkin: "Flexibel",
    checkout: "vor 10:00",
    host: "Marco - Superhost (9 Jahre, 100%, <1h)",
    distances: { palermo: "~35 km", strand: "100 m", flughafen: "~30 km" },
    pros: ["G\u00e4ste-Favorit! 4,93/5 (107 Reviews)", "100m zum Strand!", "Freistehende Villa mit Garten", "Au\u00dfenk\u00fcche + Au\u00dfendusche", "3 SZ + 2 B\u00e4der", "Superhost seit 9 Jahren"],
    cons: ["1.257\u20ac - gehoben", "~35 km bis Palermo", "Keine \u00f6ffentlichen Verkehrsmittel", "Auto zwingend n\u00f6tig"],
    quotes: [
      { text: "Klimaanlage in allen Zimmern, sehr angenehm. Marco ist sehr bem\u00fcht.", author: "Belmonte, CH" },
      { text: "Die gro\u00dfe Au\u00dfenk\u00fcche benutzten wir t\u00e4glich. Marco ist ein toller Gastgeber.", author: "Selina, DE" }
    ],
    photos: [
      { icon: "\u{1F3D6}", desc: "Strand nur 100m entfernt" },
      { icon: "\u{1F3E1}", desc: "Villa mit Garten" },
      { icon: "\u{1F373}", desc: "Au\u00dfenk\u00fcche zum Grillen" },
      { icon: "\u{1F305}", desc: "Sonnenuntergang am Meer" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#117a65,#48c9b0)", num: "#0e6655", marker: "#48c9b0" },
    mapLat: 38.0714,
    mapLng: 13.0366
  },

  // ═══════════════════════════════════════════════
  //  MEINE AUSWAHL
  // ═══════════════════════════════════════════════
  {
    id: 17,
    name: "Villa Salvatore",
    type: "Pension (B&B)",
    location: "Capaci",
    address: "Via San Giuseppe Maria Tomasi 35, 90044 Capaci",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/villa-salvatore-palermo.de.html",
    selectedBy: "",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 672,
    originalPrice: 725,
    rating: 8.0,
    ratingCount: 137,
    ratingCategories: { personal: 8.0, ausstattung: 8.5, sauberkeit: 8.8, komfort: 8.9, preisLeistung: 8.7, lage: 7.3, wlan: 8.8 },
    sqm: 32,
    bedrooms: 1,
    bathrooms: 1,
    beds: "1 Einzelbett + 2 Doppelbetten",
    maxGuests: 5,
    features: ["Balkon (Garten-/Bergblick)", "Klimaanlage", "WLAN", "Terrasse", "Kaffeemaschine", "Flachbild-TV", "Waschmaschine", "Bar", "Garten", "Frühstück"],
    parking: "",
    cancellation: { free: false, note: "Nicht kostenlos stornierbar" },
    checkin: "16:00 - 23:30",
    checkout: "05:00 - 10:00",
    host: "Angelica (spricht EN, ES, IT, RO)",
    distances: { palermo: "21 km", strand: "2,8 km", bahnhof: "1,6 km (Capaci)", flughafen: "12 km" },
    pros: ["Günstig: nur 672€ für 7 Nächte!", "Frühstück inklusive", "Großer Balkon mit Berg-/Gartenblick", "Sehr sauber (8,8/10)", "Nah am Flughafen (12 km)", "137 Bewertungen - gut belegt"],
    cons: ["21 km bis Palermo Zentrum", "Kein Parkplatz", "Nicht stornierbar", "Nur über Treppe erreichbar", "Ruhezeit 21-09 Uhr"],
    quotes: [
      { text: "Zimmer war mit großem Balkon, Blick auf die Landschaft. Zimmer sauber, alles Nötige vorhanden.", author: "Jeanina, AT" },
      { text: "Sehr freundliche Gastgeberin, tolle Aussicht und tolles Frühstück!", author: "Carlotta, DK" },
      { text: "Unterkunft sehr sauber, liebevolles Frühstück und Gastgeber sehr freundlich", author: "Matthias, DE" }
    ],
    photos: [
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit rot-weißem Bett" },
      { icon: "\u{1F305}", desc: "Balkon mit Tisch und Aussicht" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Dusche" },
      { icon: "\u{1F33F}", desc: "Garten und Terrasse" },
      { icon: "\u{1F3D4}", desc: "Bergblick vom Balkon" }
    ],
    photoCount: "50+",
    colors: { header: "linear-gradient(135deg,#b7510d,#e67e22)", num: "#935116", marker: "#e67e22" },
    mapLat: 38.1730,
    mapLng: 13.2370
  },
  {
    id: 18,
    name: "La Casa Sul Mare",
    type: "Ferienwohnung (ganze Wohnung)",
    location: "Trappeto (Strandlage!)",
    address: "90040 Trappeto",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/la-casa-sul-mare-trappeto.html",
    selectedBy: "",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 502,
    originalPrice: null,
    rating: 7.4,
    ratingCount: 7,
    ratingCategories: { personal: 8.5, ausstattung: 6.5, sauberkeit: 7.0, komfort: 7.5, preisLeistung: 7.0, lage: 9.0 },
    sqm: 47,
    bedrooms: 2,
    bathrooms: 1,
    beds: "1 Einzel + 1 Doppel (SZ1), 2 Etagenbetten (SZ2)",
    maxGuests: 5,
    features: ["Direkt am Strand (50m!)", "Meerblick", "Balkon", "Klimaanlage", "WLAN", "Küche (komplett)", "Waschmaschine", "Kaffeemaschine", "Mikrowelle", "TV", "Haustiere erlaubt"],
    parking: "Gratis Parkplatz (Straße)",
    cancellation: { free: false, note: "Nicht kostenlos stornierbar, Vorauszahlung" },
    checkin: "16:00 - 20:00",
    checkout: "00:00 - 10:00",
    host: "NOVASOL (Ferienhausagentur)",
    distances: { palermo: "~50 km", strand: "50 m (!)", bahnhof: "750 m (Trappeto)", flughafen: "15 km" },
    pros: ["Günstigste 7-Nächte-Option (502€)!", "Direkt am Strand (50m zum Meer)", "Meerblick vom Balkon", "Gratis Parkplatz", "2 Schlafzimmer (47m²)", "Haustiere erlaubt", "Eigene Küche"],
    cons: ["Nur 7 Bewertungen", "~50 km bis Palermo Zentrum", "Nicht stornierbar", "Endreinigung 50€ extra", "Kurtaxe ~1€/Person/Tag extra", "Ausstattung nur 6,5/10"],
    quotes: [],
    photos: [
      { icon: "\u{1F3D6}", desc: "Balkon mit Meerblick" },
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit Bett" },
      { icon: "\u{1F373}", desc: "Wohnküche mit Essbereich" },
      { icon: "\u{1F30A}", desc: "Strand direkt vor der Tür" },
      { icon: "\u{1F305}", desc: "Küstenblick vom Balkon" }
    ],
    photoCount: "13",
    colors: { header: "linear-gradient(135deg,#0277bd,#039be5)", num: "#01579b", marker: "#039be5" },
    mapLat: 38.0720,
    mapLng: 13.0380
  },
  {
    id: 19,
    name: "House of Lady",
    type: "Ferienwohnung (ganze Wohnung)",
    location: "Carini",
    address: "Via Foca 7, 90044 Carini",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/house-of-lady.html",
    selectedBy: "",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 718,
    originalPrice: null,
    rating: 9.4,
    ratingCount: 23,
    ratingCategories: { personal: 10.0, ausstattung: 9.6, sauberkeit: 10.0, komfort: 10.0, preisLeistung: 9.6, lage: 8.3, wlan: 8.7 },
    sqm: 110,
    bedrooms: 3,
    bathrooms: 2,
    beds: "SZ1: Doppelbett / SZ2: 2 Einzelbetten / SZ3: Doppelbett",
    maxGuests: 5,
    features: ["Meerblick", "Terrasse", "3 Schlafzimmer!", "2 Badezimmer", "Klimaanlage", "WLAN", "Küche (komplett)", "Waschmaschine", "Kaffeemaschine", "Flachbild-TV", "Schallschutz", "Haustiere erlaubt", "Flughafentransfer"],
    parking: "Gratis Privatparkplatz",
    cancellation: { free: true, note: "Kostenlos bis 21.06." },
    checkin: "15:00 - 18:00",
    checkout: "08:00 - 11:00",
    host: "Piero (Sohn spricht Englisch)",
    booking: "Buchungsanfrage (24h Antwort)",
    distances: { palermo: "~21 km", strand: "2,2 km", bahnhof: "1,8 km (Carini Torre Ciachea)", flughafen: "10 km" },
    pros: ["110m² - riesig für 5 Personen!", "3 Schlafzimmer + 2 Bäder (top!)", "9,4/10 Bewertung (Wonderful)", "Personal: perfekte 10/10", "Gratis Parkplatz auf Grundstück", "Kostenlos stornierbar bis 21.06.", "Meerblick + Terrasse"],
    cons: ["~21 km bis Palermo Zentrum", "Buchungsanfrage nötig (24h)", "Check-in nur 15-18 Uhr", "Privatstrand-Bereich (kein Sandstrand)", "Nur über Treppe erreichbar"],
    quotes: [
      { text: "As a group of five friends we really enjoyed our stay. Private parking on property was an enjoyable benefit.", author: "Hubert, PL" },
      { text: "Big Apartment for max 6 people with two toilets and very good air conditioning in every bedroom.", author: "Maximilian, AT" },
      { text: "Appartamento completo di tutto, il signor Piero è un host eccezionale e la casa è ampia e pulitissima.", author: "Federica, IT" }
    ],
    photos: [
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit Doppelbett" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Dusche" },
      { icon: "\u{1F373}", desc: "Küche mit Essbereich" },
      { icon: "\u{1F305}", desc: "Terrasse mit Meerblick" },
      { icon: "\u{1F3D6}", desc: "Strand in der Nähe" }
    ],
    photoCount: "35+",
    colors: { header: "linear-gradient(135deg,#6c3483,#a569bd)", num: "#5b2c6f", marker: "#a569bd" },
    mapLat: 38.1690,
    mapLng: 13.2280
  },

  // ═══════════════════════════════════════════════
  //  WEITERE UNTERKÜNFTE
  // ═══════════════════════════════════════════════
  {
    id: 9,
    name: "Casa Alice",
    type: "Pension",
    location: "Isola delle Femmine",
    address: "50 Via di Maggio, Isola delle Femmine",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/casa-alice-isola-delle-femmine.de.html",
    selectedBy: "",
    dateFrom: "2026-06-01",
    dateTo: "2026-06-06",
    nights: 5,
    persons: 5,
    totalPrice: 458,
    originalPrice: 491,
    rating: 9.2,
    ratingCount: 56,
    ratingCategories: { personal: 9.6, ausstattung: 8.8, sauberkeit: 9.4, komfort: 9.4, preisLeistung: 9.3, lage: 9.6, wlan: 10 },
    sqm: 35,
    bedrooms: 1,
    bathrooms: 1,
    beds: "1 Einzel + 1 Doppel + 2 Etagenbetten",
    maxGuests: 5,
    features: ["Meerblick", "Balkon", "Klimaanlage", "WLAN (13 Mbit)", "Küche", "Waschmaschine"],
    parking: "Gratis Parkplatz",
    cancellation: { free: false, note: "Nicht kostenlos stornierbar" },
    checkin: "13:00 - 21:00",
    checkout: "08:00 - 10:00",
    host: "Maria Rosa (spricht Italienisch)",
    distances: { palermo: "17 km", strand: "1,1 km", bahnhof: "450 m", flughafen: "15 km" },
    pros: ["Günstigste Option!", "Meerblick vom Balkon", "450m zum Bahnhof", "Sehr freundliche Gastgeberin", "Strand zu Fuß erreichbar"],
    cons: ["Nur 35m² für 5 Personen", "17 km bis Palermo", "Nicht stornierbar", "Nur Treppe (kein Aufzug)", "Gastgeberin nur Italienisch"],
    quotes: [{ text: "Sehr gemütlich, groß, bequeme Betten, Mikrowelle, Kühlschrank, Kaffeemaschine, große Dusche", author: "Lucia, DE" }],
    photos: [
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit Bett und Handtüchern" },
      { icon: "\u{1F6C0}", desc: "Blau gefliestes Badezimmer mit Waschbecken und Toilette" },
      { icon: "\u{1F374}", desc: "Tisch und zwei Stühle (Essbereich)" },
      { icon: "\u{1F305}", desc: "Strand mit Sonnenschirmen bei Sonnenuntergang" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Waschbecken, Badewanne und Spiegel" }
    ],
    photoCount: "55+",
    colors: { header: "linear-gradient(135deg,#2471a3,#2e86c1)", num: "#1a5276", marker: "#2980b9" },
    mapLat: 38.1828,
    mapLng: 13.2450
  },
  {
    id: 10,
    name: "Maya Palace Real",
    type: "Pension",
    location: "Palermo Zentrum (Albergaria)",
    address: "169 Via Porta di Castro, Palermo",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/maya-palace-real.de.html",
    selectedBy: "",
    dateFrom: "2026-06-01",
    dateTo: "2026-06-06",
    nights: 5,
    persons: 5,
    totalPrice: 478,
    originalPrice: 508,
    rating: 7.1,
    ratingCount: 93,
    ratingCategories: { personal: 8.0, ausstattung: 6.4, sauberkeit: 7.5, komfort: 7.4, preisLeistung: 7.2, lage: 8.4, wlan: 9.2 },
    sqm: 30,
    bedrooms: 1,
    bathrooms: 1,
    beds: "1 Einzel + 1 franz. Doppel + 1 Etagenbett",
    maxGuests: 5,
    features: ["Klimaanlage", "WLAN", "Gemeinschaftsküche"],
    parking: "",
    cancellation: { free: true, note: "Kostenlos bis 27.05." },
    checkin: "15:00 - 23:00",
    checkout: "08:00 - 10:00",
    host: "",
    distances: { palermo: "500 m", strand: "6 km", bahnhof: "550 m", flughafen: "29 km" },
    pros: ["Mitten in Palermo! (500m Kathedrale)", "Günstig", "Kostenlos stornierbar", "Guter ÖPNV"],
    cons: ["Schwächste Bewertung (7,1)", "Nur 30m² - kleinste!", "Ausstattung nur 6,4", "Kein Parkplatz", "Nur noch 1 Zimmer!"],
    quotes: [],
    photos: [
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit rotem Bett und Handtüchern" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Toilette und Glasdusche" },
      { icon: "\u{1F373}", desc: "Küche mit Holzschränken und Spüle" },
      { icon: "\u{1F4FA}", desc: "Wohnzimmer mit Sofa und Flachbildfernseher" },
      { icon: "\u26EA", desc: "Kathedrale in der Nähe" }
    ],
    photoCount: "93+",
    colors: { header: "linear-gradient(135deg,#922b21,#c0392b)", num: "#7b241c", marker: "#c0392b" },
    mapLat: 38.1095,
    mapLng: 13.3535
  },
  {
    id: 11,
    name: "Casa del Grecale",
    type: "Ferienhaus (ganzes Haus!)",
    location: "Isola delle Femmine",
    address: "5 Via Trento, Isola delle Femmine",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/appartamento-incantevole-ad-isola-delle-femmine.de.html",
    selectedBy: "",
    dateFrom: "2026-06-01",
    dateTo: "2026-06-06",
    nights: 5,
    persons: 5,
    totalPrice: 490,
    originalPrice: 528,
    rating: 9.4,
    ratingCount: 18,
    ratingCategories: { personal: 10, ausstattung: 9.5, sauberkeit: 9.9, komfort: 9.6, preisLeistung: 9.6, lage: 9.6 },
    sqm: 95,
    bedrooms: 2,
    bathrooms: 1,
    beds: "SZ1: 3 Einzelbetten / SZ2: 1 Doppelbett",
    maxGuests: 5,
    features: ["Ganzes Ferienhaus", "Meerblick", "Balkon", "Klimaanlage", "WLAN", "Spülmaschine", "Waschmaschine", "Wohnzimmer"],
    parking: "",
    cancellation: { free: false, note: "Teilweise erstattbar", partial: true },
    checkin: "ab 16:00",
    checkout: "bis 10:00",
    host: "Barbara (Top-bewertet!)",
    distances: { palermo: "17 km", strand: "1,3 km", bahnhof: "650 m", flughafen: "15 km" },
    pros: ["95m² - sehr geräumig!", "2 Schlafzimmer, perfekt für 5", "Ganzes Haus = volle Privatsphäre", "Kostenloser Flughafentransfer!", "Personal 10/10, Sauberkeit 9,9", "Meerblick, nahe am Strand"],
    cons: ["17 km bis Palermo", "Nur 1 Bad für 5 Personen", "18 Bewertungen (wenige)", "Nur teilweise erstattbar"],
    quotes: [{ text: "Fantastic home away from home that has everything you need. Very close to restaurants, shops etc.", author: "Ruthmcg, IE" }],
    photos: [
      { icon: "\u{1F3DD}", desc: "Drachen über der Insel - Panorama!" },
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit Holzbett und blauen Laken" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Waschbecken und Spiegel" },
      { icon: "\u{1F373}", desc: "Küche mit Holzschränken, Spüle und Mikrowelle" },
      { icon: "\u{1F3D6}", desc: "Strand mit vielen Leuten im Wasser" }
    ],
    photoCount: "17+",
    colors: { header: "linear-gradient(135deg,#1e8449,#27ae60)", num: "#196f3d", marker: "#2980b9" },
    mapLat: 38.1845,
    mapLng: 13.2480,
    extraTags: [{ text: "Gratis Flughafentransfer!", class: "green highlight" }]
  },
  {
    id: 13,
    name: "Home Mia",
    type: "Ferienwohnung",
    location: "Palermo Zentrum (Monte di Pietà)",
    address: "Via Carrettieri 63, Palermo",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/home-mia.de.html",
    selectedBy: "",
    dateFrom: "2026-06-08",
    dateTo: "2026-06-13",
    nights: 5,
    persons: 5,
    totalPrice: 590,
    originalPrice: 630,
    rating: 8.4,
    ratingCount: 184,
    ratingCategories: { personal: 8.4, ausstattung: 8.3, sauberkeit: 9.0, komfort: 8.9, preisLeistung: 8.7, lage: 9.2, wlan: 9.0 },
    sqm: 50,
    bedrooms: 1,
    bathrooms: 1,
    beds: "1 Einzel + 1 Doppel + 2 Schlafsofas",
    maxGuests: 5,
    features: ["Balkon", "Klimaanlage", "WLAN", "Küche", "Fahrradverleih", "Self-Check-in"],
    parking: "Gratis Parkplatz",
    cancellation: { free: true, note: "Kostenlos bis 03.06." },
    checkin: "11:00 - 18:00 (Self-Check-in!)",
    checkout: "05:00 - 10:00",
    host: "Vincenzo",
    distances: { palermo: "~1 km", strand: "5 km", bahnhof: "1,1 km", flughafen: "29 km" },
    pros: ["184 Reviews - sehr verlässlich", "Exzellente Lage (9,2)", "Modern, frisch renoviert", "Gratis Parkplatz", "Kostenlos stornierbar"],
    cons: ["50m² für 5 Personen", "Nur 1 Schlafzimmer", "Kein Strand in der Nähe", "Nur noch 1 verfügbar!"],
    quotes: [{ text: "Great location, near the cathedral, markets and old town. Modern, newly renovated.", author: "Peter, CH / Lisa, AU" }],
    photos: [
      { icon: "\u{1F3DB}", desc: "Torbogen in der Altstadt" },
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit Betten und Fenster" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Dusche" },
      { icon: "\u{1F373}", desc: "Küche mit Edelstahlherd" },
      { icon: "\u{1F374}", desc: "Esszimmer mit Tisch und Sofa" }
    ],
    photoCount: "12+",
    colors: { header: "linear-gradient(135deg,#b7950b,#d4ac0d)", num: "#9a7d0a", marker: "#c0392b" },
    mapLat: 38.1125,
    mapLng: 13.3510
  },
  {
    id: 14,
    name: "Casetta Mape",
    type: "Ferienwohnung",
    location: "Palermo Zentrum",
    address: "63 Via G. la Masa, Palermo",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/la-casetta-mape.de.html",
    selectedBy: "",
    dateFrom: "2026-06-08",
    dateTo: "2026-06-13",
    nights: 5,
    persons: 5,
    totalPrice: 517,
    originalPrice: 550,
    rating: 7.4,
    ratingCount: 185,
    ratingCategories: { personal: 8.5, ausstattung: 7.5, sauberkeit: 7.9, komfort: 8.0, preisLeistung: 7.9, lage: 8.4, wlan: 8.5 },
    sqm: 55,
    bedrooms: 0,
    bathrooms: 1,
    beds: "1 Einzel + 2 franz. Doppelbetten",
    maxGuests: 5,
    features: ["Terrasse", "Klimaanlage", "WLAN 157 MBit/s!", "Küche", "Restaurant", "24h Check-in!", "Haustiere erlaubt"],
    parking: "Parkplatz vorhanden",
    cancellation: { free: false, note: "Nicht kostenlos stornierbar" },
    checkin: "24 Stunden möglich!",
    checkout: "10:00 - 10:30",
    host: "",
    distances: { palermo: "~1,5 km", strand: "4,1 km", bahnhof: "1,1 km", flughafen: "27 km" },
    pros: ["Günstigste Palermo-Option (ZR 2)", "Schnellstes WLAN (157 MBit/s)", "24h Check-in!", "Restaurant + Zimmerservice", "Haustiere erlaubt"],
    cons: ["Bewertung unter Durchschnitt (7,4)", "Sauberkeit nur 7,9", "Nicht kostenlos stornierbar", "Kein Strand in der Nähe"],
    quotes: [],
    photos: [
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit Bett und Bild" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Toilette" },
      { icon: "\u{1F373}", desc: "Küche mit Spüle und Herd" }
    ],
    photoCount: "20+",
    colors: { header: "linear-gradient(135deg,#7d6608,#b7950b)", num: "#6e5c07", marker: "#c0392b" },
    mapLat: 38.1248,
    mapLng: 13.3465
  },
  {
    id: 15,
    name: "Casa Marta",
    type: "Ferienwohnung",
    location: "Palermo (Außenbezirk)",
    address: "Viale della Regione Siciliana, Palermo",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/casa-marta-palermo.de.html",
    selectedBy: "",
    dateFrom: "2026-06-08",
    dateTo: "2026-06-13",
    nights: 5,
    persons: 5,
    totalPrice: 612,
    originalPrice: 654,
    rating: 8.8,
    ratingCount: 9,
    ratingCategories: { personal: 9.0, ausstattung: 8.4, sauberkeit: 9.3, komfort: 9.0, preisLeistung: 9.0, lage: 8.7 },
    sqm: 100,
    bedrooms: 2,
    bathrooms: 1,
    beds: "SZ1: Doppel / SZ2: Doppel / WZ: Schlafsofa",
    maxGuests: 5,
    features: ["Balkon (Stadtblick)", "Klimaanlage", "Küche", "Waschmaschine", "Safe"],
    parking: "Gratis Parkplatz an Unterkunft!",
    cancellation: { free: true, note: "Kostenlos bis 01.06." },
    checkin: "15:00 - 16:00 (nur 1h!)",
    checkout: "10:00 - 11:00",
    host: "",
    booking: "Buchungsanfrage (24h Antwort)",
    distances: { palermo: "3,6 km", strand: "5 km", bahnhof: "1,3 km", flughafen: "24 km" },
    pros: ["100m² - am meisten Platz!", "2 Schlafzimmer, ideal für 5", "Parkplatz direkt an Unterkunft", "Kaffeemaschine + Starterkapseln", "Niedrige Kaution (150 Euro)"],
    cons: ["3,6 km bis Kathedrale", "Buchungsanfrage nötig", "Nur 9 Bewertungen", "Check-in nur 15-16 Uhr!", "Kein WLAN erwähnt"],
    quotes: [{ text: "Preis-Leistungs-Verhältnis super. Einladend, elegant, modern und sauber.", author: "Giorgia, IT" }],
    photos: [
      { icon: "\u{1F3DB}", desc: "Flur mit Bildern - modern" },
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit Bett" },
      { icon: "\u{1F373}", desc: "Küche und Esszimmer" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Badewanne" }
    ],
    photoCount: "6",
    colors: { header: "linear-gradient(135deg,#784212,#a04000)", num: "#6e2c00", marker: "#c0392b" },
    mapLat: 38.1275,
    mapLng: 13.3200
  }
];
