/**
 * Hotel-Daten für Sizilien Urlaub Juni 2026
 *
 * Neue Unterkunft hinzufügen:
 * 1. Objekt nach dem Schema unten ans Array anhängen
 * 2. Seite neu laden – Karte, Tabellen und Detailkarten werden automatisch generiert
 *
 * Oder: das Formular auf der Seite benutzen (Abschnitt "Unterkunft hinzufügen")
 *
 * Reihenfolge: Sebas-Vorschläge zuerst, dann Rest
 */

const HOTELS = [
  // ═══════════════════════════════════════════════
  //  SEBAS-VORSCHLÄGE (oben im Ranking)
  // ═══════════════════════════════════════════════
  {
    id: 3,
    name: "Villetta \u201EAnnina\u201C",
    type: "Privatunterkunft",
    location: "Trabia",
    address: "Trabia, Sizilien",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/654922789165519047?adults=5&check_in=2026-06-22&check_out=2026-06-29",
    selectedBy: "Sebas",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 1168,
    originalPrice: null,
    rating: 4.95,
    ratingScale: 5,
    ratingCount: 82,
    ratingCategories: { sauberkeit: 5.0, genauigkeit: 4.9, checkin: 5.0, kommunikation: 4.9, lage: 4.8, preisLeistung: 5.0 },
    sqm: null,
    bedrooms: 2,
    bathrooms: 3,
    beds: "1 Doppelzimmer + 2 Einzelbetten + Schlafsofa",
    maxGuests: 6,
    features: ["Strandzugang (150m)", "Meerblick", "K\u00fcche", "WLAN", "Carport (4 Pl\u00e4tze)", "HDTV", "Waschmaschine", "Terrasse/Veranda", "Klimaanlage", "Haustiere erlaubt"],
    parking: "Gratis Carport (4 Stellpl\u00e4tze)",
    cancellation: { free: true, note: "Kostenlos bis 17.06." },
    checkin: "Flexibel",
    checkout: "vor 10:00",
    host: "Francesco - Superhost (9 Jahre, 100%, <1h)",
    distances: { palermo: "~40 km", strand: "150 m", flughafen: "~50 km" },
    pros: ["Top 5% auf Airbnb!", "4,95/5 (82 Reviews)", "Nur 150m zum Strand!", "3 Badezimmer", "Gro\u00dfe Terrasse mit Meerblick", "Neubau, alles neu"],
    cons: ["~40 km bis Palermo", "Kein Rauch-/CO-Melder", "Treppensteigen erforderlich", "Autobahnn\u00e4he (evtl. L\u00e4rm)"],
    quotes: [
      { text: "Exzellentes Haus mit drei Balkonen und Terrassen. Sehr gut eingerichtet.", author: "Matthias, DE" },
      { text: "Tolles Appartment, alles ist neu und genau wie in der Beschreibung!", author: "Malte, DE" }
    ],
    photos: [
      { icon: "\u{1F3D6}", desc: "Goldener Sandstrand von Vetrana" },
      { icon: "\u{1F6CC}", desc: "Doppelzimmer mit Meerblick" },
      { icon: "\u{1F33F}", desc: "Terrasse mit Obstb\u00e4umen" },
      { icon: "\u{1F30A}", desc: "Panorama-Meerblick" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#0e6655,#1abc9c)", num: "#0b5345", marker: "#1abc9c" },
    mapLat: 37.9978,
    mapLng: 13.6480
  },
  {
    id: 4,
    name: "MetaM Apt",
    type: "Apartment",
    location: "Palermo Stadtzentrum",
    address: "Palermo Stadtzentrum, Sizilien",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/1184002955171676231?adults=5&check_in=2026-06-22&check_out=2026-06-29",
    selectedBy: "Sebas",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 1106,
    originalPrice: null,
    rating: 4.64,
    ratingScale: 5,
    ratingCount: 11,
    ratingCategories: { sauberkeit: 4.8, genauigkeit: 4.8, checkin: 4.6, kommunikation: 4.2, lage: 4.7, preisLeistung: 4.4 },
    sqm: null,
    bedrooms: 2,
    bathrooms: 1,
    beds: "2\u00d7 Queensize-Bett + 1 Einzelbett (Loft)",
    maxGuests: 5,
    features: ["K\u00fcche", "WLAN", "TV", "Aufzug", "Waschmaschine", "Klimaanlage", "Balkon + Terrasse", "F\u00f6hn", "Freskendecke"],
    parking: "",
    cancellation: { free: true, note: "Kostenlos bis 17.06." },
    checkin: "15:00 - 20:00",
    checkout: "vor 10:00",
    host: "Wonderful Italy Sicilia (100%, <1h)",
    distances: { palermo: "zentral", strand: "~3 km", bahnhof: "3,5 km", flughafen: "~40 Min." },
    pros: ["100% Lage-Bewertung 5 Sterne!", "Freskendecke + historisches Geb\u00e4ude", "Aufzug vorhanden", "Mitten in Palermo"],
    cons: ["Kommunikation nur 4,2", "Kein Rauch-/CO-Melder", "Kein Parkplatz", "1. OG = relativ dunkel", "Check-in nur bis 20:00 (Aufpreis 20\u20ac)"],
    quotes: [
      { text: "Die Lage ist perfekt um \u00fcberall zu Fu\u00df hinzugelangen.", author: "Vivien, DE" },
      { text: "Sehr sch\u00f6ne Wohnung, sch\u00f6n eingerichtet, im Herzen von Palermo.", author: "Alessandra, IT" }
    ],
    photos: [
      { icon: "\u{1F3DB}", desc: "Historisches Geb\u00e4ude mit Fresken" },
      { icon: "\u{1F6CC}", desc: "Queensize-Bett mit Loft" },
      { icon: "\u{1F373}", desc: "Offene K\u00fcche mit Essbereich" },
      { icon: "\u{1F305}", desc: "Balkon mit Platzblick" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#cb4335,#e74c3c)", num: "#a93226", marker: "#e74c3c" },
    mapLat: 38.1157,
    mapLng: 13.3615
  },
  {
    id: 5,
    name: "Casa Mareluna",
    type: "Privatunterkunft (3 Etagen)",
    location: "Porticello",
    address: "Porticello, Sizilien",
    platform: "Airbnb",
    link: "https://www.airbnb.de/rooms/1364533074420730446?adults=5&check_in=2026-06-22&check_out=2026-06-29",
    selectedBy: "Sebas",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 1159,
    originalPrice: null,
    rating: 5.0,
    ratingScale: 5,
    ratingCount: 4,
    ratingCategories: { sauberkeit: 5.0, genauigkeit: 5.0, checkin: 5.0, kommunikation: 5.0, lage: 4.8, preisLeistung: 4.8 },
    sqm: null,
    bedrooms: 3,
    bathrooms: 2,
    beds: "Doppelbett + 2 Einzelbetten + Einzelbett",
    maxGuests: 5,
    features: ["Hofblick", "Stadtblick", "Strandzugang", "K\u00fcche", "WLAN", "Arbeitsplatz", "Parkplatz", "TV", "Waschmaschine", "Klimaanlage", "Panoramaterrassen"],
    parking: "Gratis Parkplatz",
    cancellation: { free: true, note: "Kostenlos bis 08.06." },
    checkin: "15:00 - 20:00",
    checkout: "vor 10:00",
    host: "Oscar - Superhost (4 Jahre, 100%, <1h)",
    distances: { palermo: "~20 km", strand: "wenige Minuten" },
    pros: ["Perfekte 5,0/5 Sterne!", "3 Schlafzimmer + 2 B\u00e4der", "Komplett renoviert, 3 Etagen", "Charmantes Fischerdorf", "Gro\u00dfe Panoramaterrassen"],
    cons: ["Nur 4 Bewertungen", "~20 km bis Palermo", "Max. 5 G\u00e4ste (knapp)"],
    quotes: [
      { text: "Oscar ist ein freundlicher Gastgeber. Das Haus ist komplett ausgestattet und hat alles zum Entspannen.", author: "Romy, DE" },
      { text: "Toller Aufenthalt in Porticello. Das Haus ist sch\u00f6n und gut eingerichtet.", author: "Laurent, FR" }
    ],
    photos: [
      { icon: "\u{1F6A2}", desc: "Fischerhafen Porticello" },
      { icon: "\u{1F6CC}", desc: "Elegantes Schlafzimmer" },
      { icon: "\u{1F305}", desc: "Panoramaterrasse mit Meerblick" },
      { icon: "\u{1F373}", desc: "Moderne K\u00fcche" }
    ],
    photoCount: "alle",
    colors: { header: "linear-gradient(135deg,#1a5276,#2e86c1)", num: "#154360", marker: "#2e86c1" },
    mapLat: 38.0862,
    mapLng: 13.5305
  },

  // ═══════════════════════════════════════════════
  //  WEITERE AUSWAHL
  // ═══════════════════════════════════════════════
  {
    id: 15,
    name: "Casa Marta",
    type: "Ferienwohnung",
    location: "Palermo (Au\u00dfenbezirk)",
    address: "Viale della Regione Siciliana, Palermo",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/casa-marta-palermo.de.html",
    selectedBy: "",
    dateFrom: "2026-06-08",
    dateTo: "2026-06-13",
    nights: 5,
    persons: 5,
    totalPrice: 612,
    originalPrice: 654,
    rating: 8.8,
    ratingCount: 9,
    ratingCategories: { personal: 9.0, ausstattung: 8.4, sauberkeit: 9.3, komfort: 9.0, preisLeistung: 9.0, lage: 8.7 },
    sqm: 100,
    bedrooms: 2,
    bathrooms: 1,
    beds: "SZ1: Doppel / SZ2: Doppel / WZ: Schlafsofa",
    maxGuests: 5,
    features: ["Balkon (Stadtblick)", "Klimaanlage", "K\u00fcche", "Waschmaschine", "Safe"],
    parking: "Gratis Parkplatz an Unterkunft!",
    cancellation: { free: true, note: "Kostenlos bis 01.06." },
    checkin: "15:00 - 16:00 (nur 1h!)",
    checkout: "10:00 - 11:00",
    host: "",
    booking: "Buchungsanfrage (24h Antwort)",
    distances: { palermo: "3,6 km", strand: "5 km", bahnhof: "1,3 km", flughafen: "24 km" },
    pros: ["100m\u00b2 - am meisten Platz!", "2 Schlafzimmer, ideal f\u00fcr 5", "Parkplatz direkt an Unterkunft", "Kaffeemaschine + Starterkapseln", "Niedrige Kaution (150 Euro)"],
    cons: ["3,6 km bis Kathedrale", "Buchungsanfrage n\u00f6tig", "Nur 9 Bewertungen", "Check-in nur 15-16 Uhr!", "Kein WLAN erw\u00e4hnt"],
    quotes: [{ text: "Preis-Leistungs-Verh\u00e4ltnis super. Einladend, elegant, modern und sauber.", author: "Giorgia, IT" }],
    photos: [
      { icon: "\u{1F3DB}", desc: "Flur mit Bildern - modern" },
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit Bett" },
      { icon: "\u{1F373}", desc: "K\u00fcche und Esszimmer" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Badewanne" }
    ],
    photoCount: "6",
    colors: { header: "linear-gradient(135deg,#784212,#a04000)", num: "#6e2c00", marker: "#c0392b" },
    mapLat: 38.1275,
    mapLng: 13.3200
  },
  {
    id: 17,
    name: "Villa Salvatore",
    type: "Pension (B&B)",
    location: "Capaci",
    address: "Via San Giuseppe Maria Tomasi 35, 90044 Capaci",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/villa-salvatore-palermo.de.html",
    selectedBy: "",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 672,
    originalPrice: 725,
    rating: 8.0,
    ratingCount: 137,
    ratingCategories: { personal: 8.0, ausstattung: 8.5, sauberkeit: 8.8, komfort: 8.9, preisLeistung: 8.7, lage: 7.3, wlan: 8.8 },
    sqm: 32,
    bedrooms: 1,
    bathrooms: 1,
    beds: "1 Einzelbett + 2 Doppelbetten",
    maxGuests: 5,
    features: ["Balkon (Garten-/Bergblick)", "Klimaanlage", "WLAN", "Terrasse", "Kaffeemaschine", "Flachbild-TV", "Waschmaschine", "Bar", "Garten", "Fr\u00fchst\u00fcck"],
    parking: "",
    cancellation: { free: false, note: "Nicht kostenlos stornierbar" },
    checkin: "16:00 - 23:30",
    checkout: "05:00 - 10:00",
    host: "Angelica (spricht EN, ES, IT, RO)",
    distances: { palermo: "21 km", strand: "2,8 km", bahnhof: "1,6 km (Capaci)", flughafen: "12 km" },
    pros: ["G\u00fcnstig: nur 672\u20ac f\u00fcr 7 N\u00e4chte!", "Fr\u00fchst\u00fcck inklusive", "Gro\u00dfer Balkon mit Berg-/Gartenblick", "Sehr sauber (8,8/10)", "Nah am Flughafen (12 km)", "137 Bewertungen - gut belegt"],
    cons: ["21 km bis Palermo Zentrum", "Kein Parkplatz", "Nicht stornierbar", "Nur \u00fcber Treppe erreichbar", "Ruhezeit 21-09 Uhr"],
    quotes: [
      { text: "Zimmer war mit gro\u00dfem Balkon, Blick auf die Landschaft. Zimmer sauber, alles N\u00f6tige vorhanden.", author: "Jeanina, AT" },
      { text: "Sehr freundliche Gastgeberin, tolle Aussicht und tolles Fr\u00fchst\u00fcck!", author: "Carlotta, DK" },
      { text: "Unterkunft sehr sauber, liebevolles Fr\u00fchst\u00fcck und Gastgeber sehr freundlich", author: "Matthias, DE" }
    ],
    photos: [
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit rot-wei\u00dfem Bett" },
      { icon: "\u{1F305}", desc: "Balkon mit Tisch und Aussicht" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Dusche" },
      { icon: "\u{1F33F}", desc: "Garten und Terrasse" },
      { icon: "\u{1F3D4}", desc: "Bergblick vom Balkon" }
    ],
    photoCount: "50+",
    colors: { header: "linear-gradient(135deg,#b7510d,#e67e22)", num: "#935116", marker: "#e67e22" },
    mapLat: 38.1730,
    mapLng: 13.2370
  },
  {
    id: 19,
    name: "House of Lady",
    type: "Ferienwohnung (ganze Wohnung)",
    location: "Carini",
    address: "Via Foca 7, 90044 Carini",
    platform: "Booking.com",
    link: "https://www.booking.com/hotel/it/house-of-lady.html",
    selectedBy: "",
    dateFrom: "2026-06-22",
    dateTo: "2026-06-29",
    nights: 7,
    persons: 5,
    totalPrice: 718,
    originalPrice: null,
    rating: 9.4,
    ratingCount: 23,
    ratingCategories: { personal: 10.0, ausstattung: 9.6, sauberkeit: 10.0, komfort: 10.0, preisLeistung: 9.6, lage: 8.3, wlan: 8.7 },
    sqm: 110,
    bedrooms: 3,
    bathrooms: 2,
    beds: "SZ1: Doppelbett / SZ2: 2 Einzelbetten / SZ3: Doppelbett",
    maxGuests: 5,
    features: ["Meerblick", "Terrasse", "3 Schlafzimmer!", "2 Badezimmer", "Klimaanlage", "WLAN", "K\u00fcche (komplett)", "Waschmaschine", "Kaffeemaschine", "Flachbild-TV", "Schallschutz", "Haustiere erlaubt", "Flughafentransfer"],
    parking: "Gratis Privatparkplatz",
    cancellation: { free: true, note: "Kostenlos bis 21.06." },
    checkin: "15:00 - 18:00",
    checkout: "08:00 - 11:00",
    host: "Piero (Sohn spricht Englisch)",
    booking: "Buchungsanfrage (24h Antwort)",
    distances: { palermo: "~21 km", strand: "2,2 km", bahnhof: "1,8 km (Carini Torre Ciachea)", flughafen: "10 km" },
    pros: ["110m\u00b2 - riesig f\u00fcr 5 Personen!", "3 Schlafzimmer + 2 B\u00e4der (top!)", "9,4/10 Bewertung (Wonderful)", "Personal: perfekte 10/10", "Gratis Parkplatz auf Grundst\u00fcck", "Kostenlos stornierbar bis 21.06.", "Meerblick + Terrasse"],
    cons: ["~21 km bis Palermo Zentrum", "Buchungsanfrage n\u00f6tig (24h)", "Check-in nur 15-18 Uhr", "Privatstrand-Bereich (kein Sandstrand)", "Nur \u00fcber Treppe erreichbar"],
    quotes: [
      { text: "As a group of five friends we really enjoyed our stay. Private parking on property was an enjoyable benefit.", author: "Hubert, PL" },
      { text: "Big Apartment for max 6 people with two toilets and very good air conditioning in every bedroom.", author: "Maximilian, AT" },
      { text: "Appartamento completo di tutto, il signor Piero \u00e8 un host eccezionale e la casa \u00e8 ampia e pulitissima.", author: "Federica, IT" }
    ],
    photos: [
      { icon: "\u{1F6CC}", desc: "Schlafzimmer mit Doppelbett" },
      { icon: "\u{1F6C0}", desc: "Badezimmer mit Dusche" },
      { icon: "\u{1F373}", desc: "K\u00fcche mit Essbereich" },
      { icon: "\u{1F305}", desc: "Terrasse mit Meerblick" },
      { icon: "\u{1F3D6}", desc: "Strand in der N\u00e4he" }
    ],
    photoCount: "35+",
    colors: { header: "linear-gradient(135deg,#6c3483,#a569bd)", num: "#5b2c6f", marker: "#a569bd" },
    mapLat: 38.1690,
    mapLng: 13.2280
  }
];
